import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {DarkModeProvider, useDarkMode} from "@/app/contexts/DarkModeContext";
import Menubar from "@/app/elearning/(components)/menubar";
import Theme from "@/app/contexts/ThemeProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning>
                <body className={inter.className}>
                <Theme>

                <Menubar />
                    <div className="dark:bg-slate-800 min-h-screen">
                        {children}
                    </div>
                </Theme>

                </body>
        </html>
    )
}
